baseURL = 'https://tama-jp.github.io/'
languageCode = 'ja'
title = 'たまたんぶろぐ'
#theme = "hugo-scroll" # だめ
#theme = "mainroad"
theme = "showfolio"
#theme = "ananke"


#[params]
#mainSections = ['blog']
