baseURL = 'https://tama-jp.github.io/'
languageCode = 'ja'
title = 'Ko-Da-Wa-Ri'

# git submodule add https://github.com/wayjam/hugo-theme-fluency.git themes/fluency
theme = 'fluency'

summaryLength = 100 # Configure how long the post summary should be on the homepage.
pygmentsUseClasses = true # enable theme-defined highlight style
pygmentsCodefences = true
# 日本語の文字数を正しく数えて、短いサマリーを表示できるようにするには、設定ファイルで下記のように hasCJKLanguage を true に設定します。
hasCJKLanguage = true
enableEmoji = true

googleAnalytics = "G-788BH2CZ5H"

[minify]
disableSVG = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "Tech"
tag = "tags"
archive = "archives"

[params]
author = "tama-tan"
description = "たまたんの適当なブログ"
# copyright = "© 2021 &nbsp;<a href='https://github.com/wayjam/hugo-theme-fluency'>Hugo Theme Fluency</a>"

mainSections = ["posts"]

[params.pageSize]
index = 5
list = 10
archives = 20

disableSocialShare = false
disableIndexSummary = false
disableAnchorHeading = false
disableBreadcrumb = false

disableComment = false
disableCommentByType = ["page"]
#thirdPartyComment = "this is your comment"
mathRender = true
enableFullContentRSS = true

# customScript = "<script>console.log('hello world')</script>"

[menu]
    [[menu.main]]
        identifier = "blog"
        name = "blog"
        url = "posts/"
        weight = 1
    [[menu.main]]
        identifier = "tags"
        name = "tags"
        url = "tags/"
        weight = 2
        [[menu.main]]
        identifier = "archives"
        name = "archives"
        url = "archives/"
        weight = 3
    [[menu.main]]
        identifier = "about"
        name = "about"
        url = "about/"
        weight = 4

    [[menu.footer]]
        identifier = "x"
        url = "https://x.com/tama_jp"
        name = "x"
    [[menu.footer]]
        identifier = "github"
        url = "https://github.com/tama-jp"
        name = "Github"

[privacy]
    [privacy.disqus]
        disable = false
    [privacy.googleAnalytics]
        anonymizeIP = false
        disable = false
        respectDoNotTrack = false
        useSessionStorage = false
    [privacy.instagram]
        disable = false
        simple = false
    [privacy.twitter]
        disable = false
        enableDNT = false
        simple = false
    [privacy.vimeo]
        disable = false
        enableDNT = false
        simple = false
    [privacy.youtube]
        disable = false
        privacyEnhanced = false